# Generated by Django 4.0.6 on 2022-09-16 21:53

from django.db import migrations, models
import vid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=200)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to=vid.models.video_directory_path)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('video_status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transcode_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
